DEFAULT_FOLDER = redox/rev1/base

# Disable unsupported hardware
AUDIO_SUPPORTED = no
BACKLIGHT_SUPPORTED = no

BOOTLOADER = caterina
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = yes
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
BACKLIGHT_SUPPORTED = no
MIDI_ENABLE = no
UNICODE_ENABLE = no
BLUETOOTH_ENABLE = no
AUDIO_ENABLE = no
AUDIO_SUPPORTED = no
FAUXCLICKY_ENABLE = no
RGBLIGHT_ENABLE = no
TAP_DANCE_ENABLE = yes
SEND_STRING_ENABLE = yes

SPLIT_KEYBOARD = yes
VIA_ENABLE = yes

CAPS_WORD_ENABLE = yes

OS_DETECTION_ENABLE = yes
RAW_ENABLE = yes
WPM_ENABLE = no
LEADER_ENABLE = yes

DEFAULT_FOLDER = redox/rev1
